name: "Weather Action"
description: "Get weather"
inputs:
  lat:
    description: "lat"
    required: true
    default: "31.23"
  long:
    description: "long"
    required: true
    default: "121.47"
outputs:
  temperature:
    description: "Temperature for passed lat/long"
  place:
    description: "Name of the passed place"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "cloud"
  color: "blue"
